const {test,after,before}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
process.env.DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'impulso-test-'));const {server,db,validSubscription,reminders}=require('../server');let base;const token='a'.repeat(64);const request=(route,method='GET',data,key=token)=>fetch(base+'/api/'+route,{method,headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});
before(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port});after(async()=>{await new Promise(r=>server.close(r));db.close();fs.rmSync(process.env.DATA_DIR,{recursive:true,force:true})});
test('Crear, guardar, completar y eliminar tareas; aislamiento entre dispositivos',async()=>{assert.equal((await request('state','GET',null,'invalid')).status,401);let r=await request('tasks','POST',{title:'Resolver taller',subject:'Robótica I',description:'Ejercicios 1 al 4',due:'2026-10-12'});assert.equal(r.status,201);let s=await(await request('state')).json();assert.equal(s.tasks.length,1);const id=s.tasks[0].id;assert.equal((await(await request('state','GET',null,'b'.repeat(64))).json()).tasks.length,0);await request('tasks/'+id,'PATCH',{completed:true});s=await(await request('state')).json();assert.equal(s.streak,1);assert.ok(s.tasks[0].completedDay);await request('tasks/'+id,'DELETE');assert.equal((await(await request('state')).json()).tasks.length,0)});
test('Validación y destinos seguros para push',async()=>{assert.equal((await request('tasks','POST',{title:'',subject:'Otra',description:''})).status,400);assert.equal(validSubscription({endpoint:'https://127.0.0.1/',keys:{auth:'x',p256dh:'x'}}),false);assert.equal(validSubscription({endpoint:'https://web.push.apple.com/abc',keys:{auth:'x',p256dh:'x'}}),true);assert.equal((await request('test-notification','POST',{})).status,400)});
test('Página, estado del servicio y manifiesto disponibles',async()=>{assert.deepEqual(await fetch(base+'/healthz').then(r=>r.json()),{ok:true});const r=await fetch(base);assert.equal(r.status,200);assert.match(await r.text(),/Pequeños pasos/);assert.equal((await fetch(base+'/manifest.json').then(r=>r.json())).display,'standalone')});

test('Planificador: una vez al día, después de clases y solo con pendientes',async()=>{
 const webpush=require('web-push'),original=webpush.sendNotification;let sent=0;
 webpush.sendNotification=async()=>{sent++};
 const key='c'.repeat(64);const s={tasks:[{title:'Taller',subject:'Robótica I',completedDay:null}],settings:{},subscription:{},lastSent:null};
 db.prepare('INSERT INTO profiles VALUES (?,?)').run(key,JSON.stringify(s));
 try{await reminders(new Date('2026-10-05T16:59:00-05:00'));assert.equal(sent,0);await reminders(new Date('2026-10-05T17:00:00-05:00'));assert.equal(sent,1);await reminders(new Date('2026-10-05T17:01:00-05:00'));assert.equal(sent,1);await reminders(new Date('2026-10-06T18:00:00-05:00'));assert.equal(sent,2);const updated=JSON.parse(db.prepare('SELECT state FROM profiles WHERE token=?').get(key).state);updated.tasks[0].completedDay='2026-10-06';db.prepare('UPDATE profiles SET state=? WHERE token=?').run(JSON.stringify(updated),key);await reminders(new Date('2026-10-07T18:00:00-05:00'));assert.equal(sent,2)}finally{webpush.sendNotification=original;db.prepare('DELETE FROM profiles WHERE token=?').run(key)}
});
